baseurl = "https://www.example.com/"
title = "Anup Anand Singh"
author = "Anup Anand Singh"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Anup Anand Singh"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
[[menu.main]]
    name = "Projects"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
[[menu.main]]
    name = "Resume"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"

