# Site settings
baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Olga Site"
theme = "black-and-light"
enableRobotsTXT = true

# Content sections to show on homepage
[params]
  mainSections = ["posts"]
  description = "A Hugo site using Black & Light theme"
  author = "Anup Anand Singh"

# Menu (optional)
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

# Social links (optional)
[social]
  github = "https://github.com/anupanandsingh"
  twitter = "https://twitter.com/yourhandle"
  linkedin = "https://linkedin.com/in/yourprofile"
