baseURL = "https://anupanandsingh.github.io/Olga/"
languageCode = "en-us"
title = "Olga Site"
theme = "black-and-light"
enableRobotsTXT = true

[params]
  description = "A Hugo site using Black & Light theme"
  author = "Anup Anand Singh"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

[social]
  github = "https://github.com/anupanandsingh"
