baseurl = "https://anupanand.space/"
title = "Anup Anand Singh"
author = "Anup Anand Singh"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

# Disable Hugo taxonomy kinds (tags/categories)
disableKinds = ["taxonomy", "term"]

[params]
    sitename = "Anup Anand Singh"
  disableWebFonts = false
    math = true

[[menu.main]]
    name = "Research"
    url  = "/research/"
    weight = 10
[[menu.main]]
    name = "Blog"
    url  = "https://anupanandsingh.wordpress.com"
    weight = 40
[[menu.main]]
    name = "Talks"
    url  = "/talks/"
    weight = 20

[[menu.main]]
    name = "Teaching"
    url  = "/teaching/"
    weight = 30

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[taxonomies]

