baseurl = "https://anupanand.space/"
title = "Anup Anand Singh"
author = "Anup Anand Singh"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

# Disable Hugo taxonomy kinds (tags/categories)
disableKinds = ["taxonomy", "term"]

[params]
    sitename = "Anup Anand Singh"
  disableWebFonts = false
    math = true

[[menu.main]]
    name = "Blog"
    url  = "https://anupanandsingh.wordpress.com"
    weight = 10
[[menu.main]]
    name = "Research"
    url  = "/research/"
    weight = 20
[[menu.main]]
    name = "Talks"
    url  = "/talks/"
    weight = 30
[[menu.main]]
    name = "More"
    identifier = "more"
    weight = 40
[[menu.main]]
    name = "Publications"
    url  = "/publications/"
    parent = "more"
    weight = 41
[[menu.main]]
    name = "Teaching"
    url  = "/teaching/"
    parent = "more"
    weight = 42
[[menu.main]]
    name = "Other activities"
    url  = "/activities/"
    parent = "more"
    weight = 43
[[menu.main]]
    name = "Miscellany"
    url  = "/miscellany/"
    parent = "more"
    weight = 44

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[taxonomies]

